AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9

Resources:
  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: chatbot/
      Environment:
        Variables:
          BEDROCK_MODEL_ID: us.anthropic.claude-sonnet-4-20250514-v1:0
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: "*" 
      Events:
        ChatAPI:
          Type: Api
          Properties:
            Path: /chat
            Method: post
